kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - data-science-cluster.yaml
  - odh-dashboard-config.yaml

patches:
  - path: custom-ca-bundle-patch.yaml
    target:
      kind: DSCInitialization
      name: default-dsci