---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: app-of-apps/dev
    directory:
      include: "*.yaml"
    repoURL: https://github.com/aszmuda/sno-rhoai.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true