apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lvms-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: 4.15-stable
  installPlanApproval: Automatic
  name: lvms-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
