apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: sno-lvm
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storage:
    deviceClasses:
      - fstype: xfs
        thinPoolConfig:
          sizePercent: 90
          name: thin-pool-1
          overprovisionRatio: 10
        default: true
        name: vgsno
        nodeSelector: # Determines the nodes on which to create the lvm volume group. If empty, all nodes are considered.
          nodeSelectorTerms: #A list of node selector requirements
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                    - sno-worker