---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "project.name" . | replace "_" "-" | quote }}
  labels:
    argocd.argoproj.io/managed-by: {{ $.Values.gitops_namespace }}
    {{- include "common.labels" $ | nindent 4 }}
    {{- if .Values.labels -}}
    {{ toYaml .Values.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.annotations -}}
    {{ toYaml .Values.annotations | nindent 4 }}
    {{- end }}