apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ds-projects-onboarding
  namespace: openshift-gitops
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - userId: user1
          - userId: user2
  template:
    metadata:
      name: "{{.userId}}-ds-project"
    spec:
      info:
        - name: Description
          value: Creates RHOAI Data Science projects for each userId in the list
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      project: default
      source:
        helm:
          parameters:
          - name: "name"
            value: "{{.userId}}"
        path: ds-projects-onboarding
        repoURL: 'https://github.com/aszmuda/sno-rhoai' # <7>
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc