apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhoai-prerequisites
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - appName: openshift-gitops-operator
          - appName: nfd
          - appName: nvidia-gpu
          - appName: openshift-servicemesh
          - appName: serverless-operator
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/aszmuda/sno-rhoai
        targetRevision: main
        path: "core/{{appName}}"
      destination:
        server: https://kubernetes.default.svc